### ISSUE TITLE
Broken URL link https://www.stack.nl/~marcov/buildfaq/

### ISSUE THREAD

**Issue by AndreMikulec** [castle-engine/cge-www#31]
On the page https://castle-engine.io/ios (https://github.com/castle-engine/cge-www/blob/master/htdocs/doc/ios.adoc), and under `6. More information about FPC and iOS` or `More information about FPC and iOS`, the URL link is broken: 

* https://www.stack.nl/~marcov/buildfaq/

Browsing there produces the result:
```
403 Forbidden
nginx/1.14.0 (Ubuntu)
```

An alternate URL link is here: http://www.stack.nl/~marcov/buildfaq.pdf

Information exists here at this URL: https://wiki.lazarus.freepascal.org/buildfaq

**Comment by michaliskambi** [comment]
Thanks! I added both a link to PDF and to wiki .
